### PR TITLE
Update Roll-Hack

### PR DESCRIPTION
**Pull request by NIKTONIKTO717**
Added note to the end.

### CODE REVIEW

**Comment by DJRATANMUSIC** [comment]
Hi Sir
Your Script Work But Not Withdraw Please Give Me New Update 100% Withdraw Script

**Comment by safdar2** [comment]
hey.. do you have working script please?

**Comment by somati81** [comment]
Yes I have!

ср, 23 сент. 2020 г., 04:07 safdar2 <notifications@github.com>:

**Comment by safdar2** [comment]
Can I have it please
Drop the link

**Pull request closed without merging**
